Many operations in R are vectorised, making code more efficient, concise and easier to read

In [1]:
x <- 1:4
y <- 6:9

In [2]:
x + y # No looping required, just add the 2 vectors

[1]  7  9 11 13

In [3]:
x > 2 # Gives a logical vector

[1] FALSE FALSE  TRUE  TRUE

In [4]:
x >= 2

[1] FALSE  TRUE  TRUE  TRUE

In [5]:
y == 8

[1] FALSE FALSE  TRUE FALSE

In [6]:
x * y

[1]  6 14 24 36

In [7]:
x / y

[1] 0.1666667 0.2857143 0.3750000 0.4444444

Similarly, you can add and subtruct, multiply and divide matrices together

In [16]:
x <- matrix(1:4, 2, 2)
y <- matrix(rep(10, 4), 2, 2)
print(x)
print(y)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]   10   10
[2,]   10   10


In [12]:
print(x * y) ## Element-wise multiplication

     [,1] [,2]
[1,]   10   30
[2,]   20   40


In [13]:
print(x/y) ## Element Wise Division

     [,1] [,2]
[1,]  0.1  0.3
[2,]  0.2  0.4


In [14]:
print(x%*%y) ## True matrix multiplication %*%

     [,1] [,2]
[1,]   40   40
[2,]   60   60
